### ISSUE TITLE
Can't use navigation

### ISSUE THREAD

**Issue by meliceanu** [samk-dev/nuxt-vcalendar#20]
Hi, is there a configuration i have to add to make the navigation arrows work? I don't even see the buttons being rendered in the html. Am i missing something?

<img width="270" alt="Screenshot 2024-07-22 at 14 18 47" src="https://github.com/user-attachments/assets/5a486d3f-bb1e-4f56-bde9-3934799c8ecf">

<img width="987" alt="Screenshot 2024-07-22 at 14 19 50" src="https://github.com/user-attachments/assets/1247681d-d5d1-49f8-8c10-84bddc007099">

**Comment by samk-dev** [comment]
Hey, the arrows should work without any extra configuration. did you disable the load of vcalendar css?

Could you please share a minimal reproduction so I can take a look at it?

**Comment by meliceanu** [comment]
https://github.com/user-attachments/assets/6a5994ce-5ddb-4682-94ac-ea2e9df53c6a



It seems like the whole buttons logic it's not being rendered. I imported the css normally

**Comment by meliceanu** [comment]
I'm working in Nuxt 3

**Comment by samk-dev** [comment]
I just check it in one of the projects I am using the module in, and I am not having this issue.  

Check this `https://stackblitz.com/edit/nuxt-starter-2zwgab?file=app.vue`.
Make sure you're using the `<DatePicker />` inside `<ClientOnly>` if you're using SSR

If still doesn't work could you please create a minimal repo with a minimal reproduction, with the same version of `Nuxt` and the `Module`

thanks

**Comment by meliceanu** [comment]
i followed the quick setup https://nuxt.com/modules/vcalendar, added the module and that's it. Where do i have to add the. module options?

**Comment by meliceanu** [comment]
![Uploading Screenshot 2024-07-22 at 15.27.23.png…]()

**Comment by meliceanu** [comment]
<img width="460" alt="Screenshot 2024-07-22 at 15 27 23" src="https://github.com/user-attachments/assets/7247489c-27f4-4eb3-9bd9-bdefc2d58619">

**Comment by meliceanu** [comment]
https://github.com/meliceanu/test-date-picker

**Comment by samk-dev** [comment]
in `nuxt.config` with `vcalendar` key as shown in the screenshot. 

<img width="532" alt="Screenshot 2024-07-22 at 16 30 02" src="https://github.com/user-attachments/assets/ceb33727-900f-4106-bfc2-e2e3cfad2055">

here are the module options:
<img width="554" alt="Screenshot 2024-07-22 at 16 30 53" src="https://github.com/user-attachments/assets/fd6dcfb3-4c26-4fa7-86e0-b53594466768">

is there any errors warnings in the console?

**Comment by meliceanu** [comment]
<img width="174" alt="Screenshot 2024-07-22 at 18 32 23" src="https://github.com/user-attachments/assets/196ca5c2-2b79-47fb-9134-6a5a0e54780e">





i have it but stil, the button don't work. And i have no errors in console. The Nuxt version is 3.12.3

**Comment by meliceanu** [comment]
ok i started a new nuxt 3 project and all worked, seems like something in my actual project is blocking the default styles for the date picker. even visually appears way different, even tho i can use its functionalities

**Comment by samk-dev** [comment]
I am glad that it did work. usually you don't need to put vcalendar in nuxt.config to make it work. This exists if you want to customize the calendar passing Vcalendar options.

> <img alt="Screenshot 2024-07-22 at 18 32 23" width="174" src="https://private-user-images.githubusercontent.com/126058136/351042905-196ca5c2-2b79-47fb-9134-6a5a0e54780e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzAyMDUsIm5iZiI6MTcyMTY2OTkwNSwicGF0aCI6Ii8xMjYwNTgxMzYvMzUxMDQyOTA1LTE5NmNhNWMyLTJiNzktNDdmYi05MTM0LTZhNWEwZTU0NzgwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxNzM4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDg4NTMwOTU1Nzk4ZDViYTk4NDZhY2I4OGYxYmMzMzc5MGU3NDY5OWYxNzc4ZTIxN2VhYTc4ZWY3MzMzMTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z5-NkdgQUWi41EnwGXthucsW1yfJcutiE8Goed4M5AU">
> i have it but stil, the button don't work. And i have no errors in console. The Nuxt version is 3.12.3
