### ISSUE TITLE
Failed to resolved v-calendar/style.css

### ISSUE THREAD

**Issue by noprobz09** [samk-dev/nuxt-vcalendar#5]
Hi, 

I got error upon running after installation.

`Failed to resolve import "v-calendar/style.css" from "virtual:nuxt:D:\laragon\www\myproj\todloo\frontend\.nuxt\css.mjs". Does the file exist?`

Any help and suggestion are much appreciated. Thanks.

**Comment by datenspast** [comment]
Hi, same error here.

**Comment by samk-dev** [comment]
Sorry for the late replay, I was on vacation. Could you please provide a reproduction on stackblitz or a git repository where I can take a look at the issue? I just used it in a new project with that latest version of nuxt and seems okay. Later today I will release a minor maintenance update. @noprobz09  @datenspast

**Comment by samk-dev** [comment]
@noprobz09  @datenspast  here's a stackblitz example with the latest update :)

Please update nuxt-vcalendar to the latest `version 1.0.2` and let me know if you still having issues.

best regards.
