### ISSUE TITLE
Wrong URL to Documentation / Github in Nuxt Modules

### ISSUE THREAD

**Issue by McSundae** [samk-dev/nuxt-vcalendar#9]
Hello there,
I'm not sure if this is the right place, but I don't know where to make contact else where.

Within the Nuxt Modules Page I found this, but sadly the link didn't worked since it changed from

https://github.com/samk-dev/vcalendar

to

https://github.com/samk-dev/nuxt-vcalendar

This should be updated

**Comment by samk-dev** [comment]
Hi @McSundae 

Thank you for letting me know. I will update the urls on Nuxt Modules Page as soon as I can.

**Comment by samk-dev** [comment]
closing thanks to @castrogarciajs
